In [ ]:
#SoS'26
#analysing dropout trend using data analysis
# Aim- data collection and understanding

In [ ]:
import pandas as pd
import numpy as np
# loading dataset
df_gender= pd.read_csv(' gender.csv')
df_gender

,Sl. No.,State/UT,Primary Drop Out Rate - Boys,Primary Drop Out Rate - Girls,Primary Drop Out Rate - Overall,Upper Primary Drop Out Rate - Boys,Upper Primary Drop Out Rate - Girls,Upper Primary Drop Out Rate - Overall,Secondary Drop Out Rate - Boys,Secondary Drop Out Rate - Girls,Secondary Drop Out Rate - Overall
0,1,Andaman and Nicobar Islands,0.2,0.7,0.4,0.9,1.0,1.0,6.0,3.9,5.0
1,2,Andhra Pradesh,0.0,0.0,0.0,1.7,1.5,1.6,17.5,15.0,16.3
2,3,Arunachal Pradesh,9.3,9.2,9.3,4.8,8.4,6.7,11.2,12.3,11.7
3,4,Assam,6.8,5.2,6.0,10.1,7.6,8.8,19.8,20.7,20.3
4,5,Bihar,0.0,0.0,0.0,4.0,5.2,4.6,19.5,21.4,20.5
5,6,Chandigarh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,Chhattisgarh,1.0,0.6,0.8,4.8,3.3,4.1,11.5,8.1,9.7
7,8,Dadra and Nagar Haveli and Daman and Diu,0.0,0.0,0.0,0.0,0.0,0.0,10.5,8.4,9.5
8,9,Delhi,0.0,0.0,0.0,0.0,0.0,0.0,5.9,3.7,4.8
9,10,Goa,0.0,0.0,0.0,0.0,0.0,0.0,12.1,5.5,9.0
10,11,Gujarat,0.0,0.0,0.0,4.2,5.8,5.0,19.4,15.9,17.9
11,12,Haryana,0.0,0.0,0.0,0.3,0.2,0.2,6.7,4.9,5.9
12,13,Himachal Pradesh,0.0,0.0,0.0,0.6,0.5,0.6,2.0,0.9,1.5
13,14,Jammu and Kashmir,3.9,4.1,4.0,2.8,3.2,3.0,5.6,6.3,6.0
14,15,Jharkhand,2.4,1.1,1.8,3.7,4.0,3.9,9.7,8.9,9.3
15,16,Karnataka,0.0,0.0,0.0,1.1,1.1,1.1,16.2,13.0,14.7
16,17,Kerala,0.0,0.0,0.0,0.0,0.0,0.0,6.9,4.1,5.5
17,18,Ladakh,7.5,5.5,6.5,2.2,0.0,1.1,4.0,5.7,4.9
18,19,Lakshadweep,0.5,0.4,0.5,3.2,1.9,2.6,0.4,0.0,0.0
19,20,Madhya Pradesh,3.2,2.9,3.1,8.6,9.0,8.8,10.6,9.7,10.1
20,21,Maharashtra,0.0,0.0,0.0,1.5,1.6,1.5,10.8,10.6,10.7
21,22,Manipur,13.5,13.0,13.3,6.0,5.2,5.6,1.4,1.2,1.3
22,23,Meghalaya,11.1,8.6,9.8,12.0,9.4,10.6,23.3,20.4,21.7
23,24,Mizoram,7.1,5.6,6.4,3.8,1.6,2.7,13.1,10.8,11.9
24,25,Nagaland,5.6,4.5,5.0,4.6,3.4,4.0,18.9,16.2,17.5
25,26,Odisha,0.0,0.0,0.0,8.0,6.5,7.3,29.2,25.2,27.3
26,27,Puducherry,3.7,3.6,3.7,2.8,2.1,2.4,8.4,4.1,6.3
27,28,Punjab,1.6,1.0,1.3,8.7,7.1,8.0,18.3,16.0,17.2
28,29,Rajasthan,3.8,3.3,3.6,4.4,4.2,4.3,7.8,7.5,7.7
29,30,Sikkim,2.9,0.5,1.8,0.0,0.0,0.0,14.6,9.5,11.9
30,31,Tamil Nadu,0.0,0.0,0.0,0.0,0.0,0.0,6.3,2.5,4.5
31,32,Telangana,0.0,0.0,0.0,3.4,2.9,3.1,14.5,12.9,13.7
32,33,Tripura,1.2,1.0,1.1,4.8,4.3,4.5,8.5,8.2,8.3
33,34,Uttarakhand,1.0,0.5,0.8,3.0,2.4,2.7,5.4,4.6,5.0
34,35,Uttar Pradesh,2.4,3.0,2.7,1.3,4.7,2.9,9.5,10.0,9.7
35,36,West Bengal,9.1,8.2,8.6,0.0,0.0,0.0,18.4,17.7,18.0
36,37,India,1.6,1.4,1.5,2.7,3.3,3.0,13.0,12.3,12.6

In [ ]:
df_gender.head()

,Sl. No.,State/UT,Primary Drop Out Rate - Boys,Primary Drop Out Rate - Girls,Primary Drop Out Rate - Overall,Upper Primary Drop Out Rate - Boys,Upper Primary Drop Out Rate - Girls,Upper Primary Drop Out Rate - Overall,Secondary Drop Out Rate - Boys,Secondary Drop Out Rate - Girls,Secondary Drop Out Rate - Overall
0,1,Andaman and Nicobar Islands,0.2,0.7,0.4,0.9,1.0,1.0,6.0,3.9,5.0
1,2,Andhra Pradesh,0.0,0.0,0.0,1.7,1.5,1.6,17.5,15.0,16.3
2,3,Arunachal Pradesh,9.3,9.2,9.3,4.8,8.4,6.7,11.2,12.3,11.7
3,4,Assam,6.8,5.2,6.0,10.1,7.6,8.8,19.8,20.7,20.3
4,5,Bihar,0.0,0.0,0.0,4.0,5.2,4.6,19.5,21.4,20.5

In [ ]:
df_gender.info()
df_gender.describe()
df_gender.isnull().sum()
print(df_gender.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   State/UT                               37 non-null     object
 1   Primary Drop Out Rate - Boys           37 non-null     float64
 2   Primary Drop Out Rate - Girls          37 non-null     float64
 3   Primary Drop Out Rate - Overall        37 non-null     float64
 4   Upper Primary Drop Out Rate - Boys     37 non-null     float64
 5   Upper Primary Drop Out Rate - Girls    37 non-null     float64
 6   Upper Primary Drop Out Rate - Overall  37 non-null     float64
 7   Secondary Drop Out Rate - Boys         37 non-null     float64
 8   Secondary Drop Out Rate - Girls        37 non-null     float64
 9   Secondary Drop Out Rate - Overall      37 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.0+ KB
(37, 10)

In [ ]:
# uploading dataset for level
df_level =pd.read_csv( "level.csv")
df_level.head()
df_level.info()
df_level.describe()
df_level.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 17 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sl. No.                              38 non-null     object
 1   State/UT                             38 non-null     object
 2   Primary level (I - V) - Boys         36 non-null     float64
 3   Primary level (I - V) - Girls        36 non-null     float64
 4   Primary level (I - V) - Total        36 non-null     float64
 5   Upper Primary - Boys                 36 non-null     float64
 6   Upper Primary - Girls                36 non-null     float64
 7   Upper Primary - Total                36 non-null     float64
 8   Elementary level (I - VIII) - Boys   36 non-null     float64
 9   Elementary level (I - VIII) - Girls  36 non-null     float64
 10  Elementary level (I - VIII) - Total  36 non-null     float64
 11  Secondary (IX-X) - Boys              36 non-null     float64
 12  Secondary (IX-X) - Girls             36 non-null     float64
 13  Secondary (IX-X) - Total             36 non-null     float64
 14  Higher Secondary - Boys              36 non-null     float64
 15  Higher Secondary - Girls             36 non-null     float64
 16  Higher Secondary - Total             36 non-null     float64
dtypes: float64(15), object(2)
memory usage: 5.2+ KB

Sl. No.                                0
State/UT                               0
Primary level (I - V) - Boys           2
Primary level (I - V) - Girls          2
Primary level (I - V) - Total          2
Upper Primary - Boys                   2
Upper Primary - Girls                  2
Upper Primary - Total                  2
Elementary level (I - VIII) - Boys     2
Elementary level (I - VIII) - Girls    2
Elementary level (I - VIII) - Total    2
Secondary (IX-X) - Boys                2
Secondary (IX-X) - Girls               2
Secondary (IX-X) - Total               2
Higher Secondary - Boys                2
Higher Secondary - Girls               2
Higher Secondary - Total               2
dtype: int64

In [ ]:
# dataset for trend 2017 vs 2019
df_trend = pd.read_csv(" trend.csv")
df_trend.head()
df_trend.info()
df_trend.describe()
df_trend.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State/UT                 38 non-null     object
 1   2017-18 - Primary        37 non-null     float64
 2   2017-18 - Upper Primary  37 non-null     float64
 3   2017-18 - Secondary      37 non-null     float64
 4   2018-19 - Primary        37 non-null     float64
 5   2018-19 - Upper Primary  37 non-null     float64
 6   2018-19 - Secondary      37 non-null     float64
 7   2019-20 - Primary        38 non-null     float64
 8   2019-20 - Upper Primary  38 non-null     float64
 9   2019-20 - Secondary      38 non-null     float64
dtypes: float64(9), object(1)
memory usage: 3.1+ KB

State/UT                   0
2017-18 - Primary          1
2017-18 - Upper Primary    1
2017-18 - Secondary        1
2018-19 - Primary          1
2018-19 - Upper Primary    1
2018-19 - Secondary        1
2019-20 - Primary          0
2019-20 - Upper Primary    0
2019-20 - Secondary        0
dtype: int64